### ISSUE TITLE
Doesn't compile on f32::MANTISSA_DIGITS and f64::MANTISSA_DIGITS

### ISSUE THREAD

**Issue by leanthebean** [stjepang/fastrand#2]
Hello! 

It looks like this latest release isn't compiling on f32::MANTISSA_DIGITS and f64::MANTISSA_DIGITS

https://doc.rust-lang.org/std/f32/constant.MANTISSA_DIGITS.html

<img width="731" alt="Screen Shot 2020-06-26 at 9 14 36 AM" src="https://user-images.githubusercontent.com/2285160/85878405-7d60f780-b78d-11ea-8a3a-53d06fc54628.png">

**Comment by stjepang** [comment]
Thanks for the report! Should be fixed now with a new release :)
