### ISSUE TITLE
Seeding multiple RNGs

### ISSUE THREAD

**Issue by cloudhead** [stjepang/fastrand#3]
Hey there, one issue I'm encountering with `fastrand` is that I need to essentially pass down multiple RNGs to sub-components, but I need all of them to be seeded by the original RNG in some way, to be able to reproduce behavior deterministically. With something like *SplitMix*, it's possible to split an RNG to achieve the same thing. I was wondering what the right approach would be with `fastrand`? At first I tried calling `Rng::clone()`, but this isn't implemented. Otherwise, perhaps something like this works?

```rust
let rng1 = Rng::new();
let mut rng2 = Rng::new();
rng2.seed(rng1.u64(..));
```

It would be nice to have some kind of functionality like this in the library. Happy to contribute if you think this is a good idea.

Great library by the way!

**Comment by stjepang** [comment]
I'm not familiar with SplitMix, but `Rng::clone()` should be straightforward to implement :) There's no reason why the `Clone` impl doesn't exist right now.

**Comment by cloudhead** [comment]
The main thing you get from SplitMix is a native implementation of `split :: g -> (g, g)` See https://hackage.haskell.org/package/random-1.1/docs/System-Random.html#v:split

> There's no reason why the Clone impl doesn't exist right now.

Great, I'll propose something.
